src/Entity/MetierAds.php
<?php

namespace App\Entity;

use App\Repository\MetierAdsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MetierAdsRepository::class)]
class MetierAds
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $client = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(type: 'integer')]
    private ?int $status = null;

    #[ORM\Column(length: 255)]
    private ?string $link = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $deadline = null;

    #[ORM\ManyToOne(inversedBy: 'metierAds')]
    private ?User $requested_by = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $contact_email = null;

    /**
     * @var Collection<int, MetierAdPage>
     */
    #[ORM\ManyToMany(targetEntity: MetierAdPage::class, inversedBy: 'metierAds')]
    private Collection $pages;

    public function __construct()
    {
        $this->pages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClient(): ?string
    {
        return $this->client;
    }

    public function setClient(string $client): static
    {
        $this->client = $client;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): static
    {
        $this->link = $link;

        return $this;
    }

    public function getDeadline(): ?\DateTimeInterface
    {
        return $this->deadline;
    }

    public function setDeadline(?\DateTimeInterface $deadline): static
    {
        $this->deadline = $deadline;

        return $this;
    }

    public function getRequestedBy(): ?User
    {
        return $this->requested_by;
    }

    public function setRequestedBy(?User $requested_by): static
    {
        $this->requested_by = $requested_by;

        return $this;
    }

    public function getContactEmail(): ?string
    {
        return $this->contact_email;
    }

    public function setContactEmail(?string $contact_email): static
    {
        $this->contact_email = $contact_email;

        return $this;
    }

    /**
     * @return Collection<int, MetierAdPage>
     */
    public function getPages(): Collection
    {
        return $this->pages;
    }

    public function addPage(MetierAdPage $page): static
    {
        if (!$this->pages->contains($page)) {
            $this->pages->add($page);
        }

        return $this;
    }

    public function removePage(MetierAdPage $page): static
    {
        $this->pages->removeElement($page);

        return $this;
    }
}

src/Controller/JobSeekerController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\User;
use DateTimeImmutable;
use Stripe\StripeClient;
use App\Entity\JobReport;
use App\Entity\MetierOrder;
use App\Entity\EmployerJobs;
use Symfony\Component\HttpFoundation\RequestStack;
use App\Entity\MetierGender;
use App\Entity\MetierSkills;
use App\Event\MyCustomEvent;
use App\Service\MailService;
use Stripe\Checkout\Session;
use App\Entity\MetierCareers;
use App\Entity\MetierCountry;
use App\Entity\MetierJobType;
use App\Event\SendEmailEvent;
use App\Form\MealPlannerForm;
use App\Service\FileUploader;
use App\Service\OrderService;
use App\Entity\EmployerTender;
use App\Entity\JobApplication;
use App\Entity\MetierPackages;
use App\Entity\EmployerCourses;
use App\Entity\JobSeekerResume;
use App\Entity\MetierDownloads;
use App\Form\JobSeekerInfoType;
use App\Model\ResumeStatusEnum;
use App\Service\PaymentService;
use Symfony\Component\Uid\Uuid;
use App\Entity\CourseApplication;
use App\Entity\JobSeekerJobAlert;
use App\Entity\JobSeekerLanguage;
use App\Entity\JobSeekerSavedJob;
use App\Entity\MetierJobCategory;
use App\Entity\MetierProfileView;
use App\Entity\TenderApplication;
use App\Form\JobSeekerResumeType;
use App\Entity\JobSeekerEducation;
use App\Entity\MetierOrderPayment;
use App\Entity\MetierServiceOrder;
use App\Form\JobSeekerDetailsType;
use App\Entity\JobSeekerExperience;
use App\Form\CityAutocompleteField;
use App\Form\EmailTemplateFormType;
use App\Entity\JobSeekerCertificate;
use App\Form\StateAutoCompleteField;
use App\Service\NotificationService;
use App\Form\CareerAutoCompleteField;
use App\Form\JobSeekerEducationsType;
use App\Form\JobSeekerExperienceType;
use Symfony\Component\Form\FormError;
use Symfony\Component\Form\FormEvent;
use App\Form\CountryAutoCompleteField;
use App\Form\JobSeekerCertificateType;
use Symfony\Component\Form\FormEvents;
use App\Form\JobSeekerPsReportFormType;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\EmployerJobQuestionAnswer;
use App\Entity\EmployerStaff;
use Symfony\Component\Form\FormInterface;
use Flasher\Prime\Storage\StorageInterface;
use Knp\Component\Pager\PaginatorInterface;
use App\Entity\JobApplicationQuestionAnswer;
use App\Entity\MetierDownloadable;
use App\Repository\MetierPackagesRepository;
use Symfony\Component\HttpClient\HttpClient;
use App\Repository\MetierDownloadsRepository;
use Symfony\Component\HttpFoundation\Request;
use App\Repository\MetierEmailTempsRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Repository\JobSeekerJobAlertRepository;
use App\Repository\MetierNotificationRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\HttpFoundation\JsonResponse;
use App\Form\DataTransformer\CityToNameTransformer;
use Symfony\Component\Validator\Constraints\IsTrue;
use App\Form\DataTransformer\StateToNameTransformer;
use App\Repository\EmployerStaffRepository;
use App\Repository\MetierDownloadableRepository;
use App\Repository\UserRepository;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Contracts\HttpClient\HttpClientInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\RadioType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use PhpOffice\PhpSpreadsheet\Style\NumberFormat\Wizard\Number;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Exception\FileNotFoundException;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\File as HttpFoundationFile;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

#[Route('/jobseeker')]
class JobSeekerController extends AbstractController
{
    private UrlGeneratorInterface $generator;
    private $serializer;
    private $params;
    private $stripeGateway;
    private $em;
    private $eventDispatcher;

    public function __construct(
        $stripSK,
        EventDispatcherInterface $eventDispatcher,
        EntityManagerInterface $em,
        ParameterBagInterface $params,
        private HttpClientInterface $client,
        UrlGeneratorInterface $generator,
        SerializerInterface $serializer
    ) {
        $this->generator = $generator;
        $this->serializer = $serializer;
        $this->params = $params;
        $this->em = $em;
        $this->stripeGateway = new StripeClient($stripSK);

        $this->eventDispatcher = $eventDispatcher;
    }


    #[Route('/', name: 'app_job_seeker')]
    public function index(): Response
    {

        return $this->redirectToRoute('app_home');
    }

    #[Route('/notifications', name: 'app_notifications_list')]
    public function notifications(MetierNotificationRepository $notificationRepository): Response
    {

        $nots = $notificationRepository->findLatestByUser($this->getUser());

        return $this->render('job_seeker/notifications.html.twig', [
            'nots' => $nots,
        ]);
    }
    #[Route('/jobalert', name: 'app_jobalert_set')]
    public function jobalert(
        JobSeekerJobAlertRepository $alerts,
        Request $request,
        EntityManagerInterface $em,
        UserRepository $userRepository
    ): Response {
        $user = $this->getUser();
        $activeSubscription = $userRepository->findActiveSubscription($user);
        $alert = $alerts->findOneBy(['jobseeker' => $user]);
        if (!$alert) {
            $alert = new JobSeekerJobAlert();
            $alert->setJobseeker($user);
        }
        $form = $this->createFormBuilder($alert)
            ->add('jobcategory', EntityType::class, [
                'class' => MetierJobCategory::class,
                'choice_label' => 'name',
                'multiple' => true,
                'autocomplete' => true,
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('phone', NumberType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])

            ->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            if(!$activeSubscription){
                $this->addFlash('danger', "This feature is not part of your plan. Please click here to upgrade now.");
            return $this->redirectToRoute('app_jobalert_set');
            }
            $em->persist($alert);
            $em->flush();
            $this->addFlash('success', "Successfully updated job alert");
            return $this->redirectToRoute('app_home');
        }

        return $this->render('job_seeker/jobalert.html.twig', [
            'form' => $form,
            'active' => $activeSubscription,
        ]);
    }
    #[Route('/profile', name: 'app_job_seeker_profile')]
    public function profile(
        Request $request,
        FileUploader $fileUploader,
        EntityManagerInterface $em,
        NotificationService $notificationService,
        UserRepository $userRepository,
        EmployerStaffRepository $staffs,
    ): Response {
        $user = $userRepository->find($this->getUser());

            // Check if user has job alerts set up
            if ($user && $this->isGranted('ROLE_JOBSEEKER')) {
            if ($user->getJobalerts()->isEmpty()) {
                // notyf()->warning('Your account may not have been restored.');
                // dd("yes");
                notyf()
                ->duration(10000)
                ->ripple(true)
                ->addWarning(
                    'Reminder! <a href="'.$this->generateUrl('app_jobalert_set').'" 
                    style="color: black; text-decoration: underline;">Click here</a> 
                    to choose and receive job alerts for new opportunities that match your preferences, along with interview updates via SMS and email.',
                    ['escapeMarkup' => false]
                );
                // $notyf->using('notyf')->addFlash(
                //     'warning', // or 'error', 'success', 'info'
                //     'Please <a href="'.$this->generateUrl('app_jobalert_set').'" 
                //     style="color: white; text-decoration: underline;">create job alerts</a> 
                //     to get notified about new jobs matching your preferences.',
                //     ['escapeMarkup' => false]
                // );
            }
            }
        $staff = $staffs->findOneBy(['jobseeker' => $user]);
        $countPrivateJobs = 0;

        if ($staff) {
            $employer = $staff->getEmployer();
            // dump($employer->getPrivateEmployerJobs());
            $countPrivateJobs = count($employer->getPrivateEmployerJobs());
        }
        // dump($staff);
        // dd($this->getUser()->getEmployerStaff());
        $job_seeker_details = $this->getUser()->getJobseekerDetails();

templates/job_seeker/add-experience.html.twig
{{ form_start(form, {'action': path('add_job_seeker_experience'), 'method': 'POST'}) }}
<div class="row mb-3">
    <div class="col-lg-12">
        <label  class="form-label">Is this your current employment? </label>
        {{ form_widget(form.current) }}
    </div>
    
</div>
<div class="row mb-3">
    <div class="col-lg-12 ">
        <label  class="form-label">Employment type </label>
        {{ form_widget(form.jobType, {attr: {'class': 'form-control'}}) }}
    </div>
</div>
<div class="row mb-3">
    <div class="col-lg-12">
        <label  class="form-label">Total experience</label>
    </div>
    <div class="col-md-6">
        {{ form_widget(form.experienceYears, {attr: {'class': 'form-control', 'placeholder': 'Years'}}) }}
    </div>
    <div class="col-md-6">
        {{ form_widget(form.experienceMonths, {attr: {'class': 'form-control', 'placeholder': 'Months'}}) }}
    </div>
</div>

<div class="row mb-3">
    <div class="col-lg-12">
        <label  class="form-label">Current company name</label>
        {{ form_widget(form.currentCompany, {attr: {'class': 'form-control', 'placeholder': 'Current Company'}}) }}
    </div>
</div>

{# <hr>
<div class="row">
    <div class="col-lg-12">
    <label  class="form-label">Current designation </label>
    </div>
    <input name="name" id="name" type="text" class="form-control" placeholder="Type your designation" required>
</div> #}

<div class="row mb-3">
    <div class="col-lg-12">
        <label  class="form-label">Joining date </label>
    </div>
    <div class="col-md-6">
        {{ form_widget(form.joinedYear, {attr: {'class': 'form-control', 'placeholder': 'Type joining year'}}) }}
    </div>
    <div class="col-md-6">
        {{ form_widget(form.joinedMonth, {attr: {'class': 'form-control', 'placeholder': 'Type joining month'}}) }}
    </div>
</div>

<div class="row mb-3">
    <div class="col-lg-12">
        <label  class="form-label">Current salary </label>
        {{ form_widget(form.salary, {attr: {'class': 'form-control', 'placeholder': '$'}}) }}
    </div>
</div>
<hr>
<div class="row mb-3">
    <div class="col-lg-12">
        <label  class="form-label">Notice period </label>
        {{ form_widget(form.noticePeriod, {attr: {'class': 'form-control', 'placeholder': 'Notice period'}}) }}
    </div>
</div>
{# <div class="row">
    <div class="col-lg-12">
    <label  class="form-label">Skills used </label>
    </div>
    <input name="name" id="name" type="text" class="form-control" placeholder="Type Skills used" required>
</div> #}

</div>

{{ form_end(form) }}

templates/job_seeker/apply-tender.html.twig
{% extends 'base.html.twig' %}
{% block title %}
	Apply Tender
{% endblock %}
{% block body %}
	<style>
		.min-height-200 {
			min-height: 200px;
		}
	</style>
	<div class="min-height-200">
		<section class="bg-home8" id="home">
			<div class="container">
				<nav class="d-inline-block" aria-label="breadcrumb ">
					<ol class="breadcrumb justify-content-center fs-12">
						<li class="">
							<a href="{{ path('app_home') }}">Search Tenders&nbsp; /</a>
						</li>
						<li class="pl-1">
							<a href="#">
								{{ tender.title }}&nbsp;
							</a>
						</li>
						<li class=" active" aria-current="page">
							/&nbsp;&nbsp;{{ tender.title }},
							{{ tender.employer.name|capitalizeWords }}
						</li>
					</ol>
				</nav>
				<div class="candidate-list-box card mt-4 col-lg-12">
					<div class="card-body p-4">
						<div
							class="row align-items-center">
							<!--end col-->

							<div class="row text-lg-start">
								<div class="col-lg-6">
									<div class="  me-lg-12 text-dark">
										<div class="ps-3 pt-2">
											<h6 class="fs-20">
												{{ tender.employer.name|capitalizeWords }}</h6>
											<h6>{{ tender.title }}</h6>
											<ul class="list-inline d-flex ">
												<li class="list-inline-item ">
													<p class="text-muted mb-0 ">
														<span class="text-muted fw-medium">
															<i class="fa fa-map-marker" aria-hidden="true"></i>
															&nbsp;
															{{ tender.city.name ?? '' }},
															{{ tender.city.country }}</span>
													</p>
												</li>
												{# <li>
																																																													|</li>
																																																												<li class="list-inline-item pl-1">
																																																													<p class="text-muted mb-0">
																																																														<span class="text-muted fw-medium">
																																																															<i class="fa fa-briefcase" aria-hidden="true"></i>
																																																															&nbsp;
																																																															{{ job.numberPosition }}
																																																															roles available</span>
																																																													</p>
																																																												</li> #}
												<li>
													|</li>
												<li class="list-inline-item pl-1"></li>
											</ul>
										</div>
									</div>
									<div class="btn-group">
										<a target="__blank" href="https://www.facebook.com/sharer/sharer.php?u={{ absolute_url(app.request.pathinfo) }}" class="btn btn-primary">
											<i class="fa fa-facebook-f"></i>
											Share on Facebook
										</a>
										<a target="__blank" href="https://twitter.com/intent/tweet?url={{ absolute_url(app.request.pathinfo) }}&text={{ job.title ?? '' }}" class="btn btn-info">
											<i class="fa fa-twitter"></i>
											Tweet
										</a>
										<a data-action="click->job-details#copyUrl" href="#" class="btn btn-success">
											<i class="fa fa-copy"></i>
											Copy
										</a>
									</div>
								</div>
								<div class="col-lg-6">
									<div
										class="modal-footer">
										{# <div class="sh mt-2 text-center ms-2">
																																																			<a href="#">
																																																				<i class="fa fa-share" aria-hidden="true"></i>
																																																				&nbsp; Share Job &nbsp;
																																																			</a>
																																																		</div> #}
										{% if tender_application %}
											<div class="sh mt-2 text-center ms-2">
												<a
													href="#" class="text-success fw-bold">
													{# <i class="fa fa-share" aria-hidden="true"></i> #}
													&nbsp; You applied for this Tender  &nbsp;
												</a>
											</div>
										{% else %}
											{# {% if job.externalLink == null %} #}
											{# <div class="top-login-line mt-2 text-center ms-2 ">
												<a href="{{ path('job_seeker_apply_tender', {'tender': tender.id }) }}">&nbsp; Apply Tender &nbsp;
												</a>
											</div> #}
											{# {% endif %} #}

											{# <div class="top-login-line mt-2 text-center ms-2 ">
																																																								<form action="{{ path('job_seeker_save_tender', {'tender': tender.id}) }}" method="post">
																																																									<button class="btn {{ tender.id in saved_jobs ? 'btn-light' : 'btn-outline-primary' }} fw-bold" {% if tender.id in saved_jobs %} data-bs-toggle="tooltip" data-bs-placement="top" title="Un-mark this job" {% else %} data-bs-toggle="tooltip" data-bs-placement="top" title="Save this job" {% endif %} {{ (app.user == null) ? 'disabled' : '' }} style="font-family: 'Inter', sans-serif; border: none; background: none;">
																																																										<i class="fa {{ tender.id in saved_jobs ? 'fa-bookmark text-success' : 'fa-bookmark-o' }} fw-bold" aria-hidden="true">
																																																											<span class="job-cont">
																																																												{{ tender.id in saved_jobs ? 'Saved ' : 'Save For Later' }}</span>
																																																										</i>
																																																									</button>
																																																								</form>
																																																							</div> #}
										{% endif %}
									</div>
									<div class="modal-footer">
										<ul class="list-inline d-flex  mb-3 mt-3">

											<li class="px-1">
												<p class="text-muted mb-0 ">
													<span class="text-muted fw-medium">
														Expires in<strong>
															{{ tender.expiresAt }}</strong>
													</span>
												</p>
											</li>
											<li>
												|</li>
											<li class=" pl-1">
												<p class="text-muted mb-0">
													<span class="text-muted fw-medium">
														<i>Posted
															{{ tender.postedAt }}</i>
													</span>
												</p>
											</li>
											{% if tender_application %}
												<li class=" pl-1">
													<p class="text-muted mb-0">
														<span class="text-muted fw-medium">
															<i>Applied
																{{ tender_application.createdAt|diffForHumans }}</i>
														</span>
													</p>
												</li>
											{% endif %}
										</ul>
									</div>
								</div>
							</div>

							<!--end col-->

						</div>
						<!--end row-->

					</div>
				</div>
			</div>
		</section>
		<section class="section-re-de ">
			<div class="container">
				<div class="mb-5">
					<p>
						<span class="fw-bold">Tender Title:
						</span>
						{{ tender.title ?? '' }}
					</p>
					<p>
						<span class="fw-bold">Company Name:
						</span>
						{{ tender.companyName }}
					</p>
					<p>
						<span class="fw-bold">Tender Duration:
						</span>
						{{ tender.duration }}
					</p>
					{% if tender.attachment %}
						<p>
							<span class="fw-bold">Attachment</span>
							<a class="btn btn-primary btn-lg" href="{{ asset('uploads/' ~ tender.attachment) }}" target="_blank">Preview</a>
						</p>
					{% endif %}
					<p>
						<span class="fw-bold">Funded By:
						</span>
						{{ tender.fundedBy }}
					</p>
					<p>
						<span class="fw-bold">Tender Value:
						</span>
						{{ tender.value }}
					</p>
					<p>
						<span class="fw-bold">Contact Name:
						</span>
						{{ tender.contactName }}
					</p>
					<p>
						<span class="fw-bold">Contact Email:
						</span>
						{{ tender.contactEmail }}
					</p>
					<p>
						<span class="fw-bold">Contact Phone:
						</span>
						{{ tender.contactPhone }}
					</p>
					
					<p>
						<span class="fw-bold">Project Location:
						</span>
						{{ tender.projectLocation}}
					</p>
					<p>
						<span class="fw-bold">Location:
						</span>
						{{ tender.locationString|join(', ')}}
					</p>
					<p>
						<span class="fw-bold">Skill and Experience Requirements:
						</span>
						{{ tender.skillAndExperience|nl2br}}
					</p>

				</div>
				<div class="description mb-5 mt-2">
					<h5>Scope</h5>
					<div class="">
						{{ tender.description|nl2br }}
					</div>
					
				</div>
				<p class="pb-3">
						{% set url  = tender.externalLink %}
						
						<span class="fw-bold">Link To Apply:
						</span>
						{% if url is not empty %}
							{% if url starts with 'http' %}
								<a href="{{ url }}" target="_blank">{{ url }}</a>
							{% else %}
								<a  class="btn btn-primary btn-lg" href="http://{{ url }}" target="_blank">Click Here To Apply</a>
							{% endif %}
							
						{% else %}
							<span>No URL provided.</span>
						{% endif %}
						{# <a target="_blank"  href="{{ course.externalLink }}">{{ course.externalLink }}</a> #}
					</p>
				{% if tender_application == null %}
				{% if form.vars.errors|length > 0 %}
					<div class="alert alert-danger">
						{{ form_errors(form) }}
					</div>
				{% endif %}
					<div class="card">
						<div class="card-header">
							<h5>Tender Application</h5>
						</div>
						<div class="card-body" id="tender-application-card">
							{{ form_start(form) }}
							<div class="row">
								<div class="col-md-6">
									<div class="form-group mt-2">
										<label class="form-label">Company/Applicant Name <span class="text-danger">*</span></label>
										{{ form_widget(form.companyName) }}
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group mt-2">
										<label class="form-label">Contact Email <span class="text-danger">*</span></label>
										{{ form_widget(form.companyEmail) }}
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group mt-2">
										<label class="form-label">Contact Phone <span class="text-danger">*</span></label>
										{{ form_widget(form.companyPhone) }}
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group mt-2">
										<label class="form-label">Country <span class="text-danger">*</span></label>
										{{ form_widget(form.country) }}
									</div>
								</div>
								<div class="col-md-12">
									<div class="form-group mt-2">
										<label class="form-label">Attach File</label>
									{{ form_widget(form.attachment) }}
									</div>
								</div>
								<div class="col-md-12">
									<div class="form-group mt-2">
										<label class="form-label">Description <span class="text-danger">*</span></label>
										{{ form_widget(form.description) }}
										{{ form_errors(form.description) }}
									</div>
								</div>
								<div class="col-md-12">
									<div class="form-group mt-2">
										<button class="btn btn-primary" onclick="return confirm('Are you sure you want to apply for this tender?');">Submit Application</button>
									</div>
								</div>
							</div>
							{{ form_end(form) }}
						</div>
					</div>

				{% endif %}
			</div>

		</section>

		<section style="min-height: 280px"></section>

		<section class="ftimg text-center">
			 
		</section>
		{% include 'home/_footer.html.twig' %}
		
	</div>
{% endblock %}

templates/job_seeker/notifications.html.twig
{% extends 'base.html.twig' %}
{% block title %}
	Notifications
{% endblock %}
{% block body %}
	<style>
		.min-height-200 {
			min-height: 200px;
		}
	</style>
	
    <div class="page-content">
    <section class="bg-homelogin" id="home">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-12">
            <div class="mb-2 pb-3 me-lg-6 text-center">
              <h1 class="display-5 fw-semibold mb-3 mt-3 fs-22">Notifications</h1>
              <p class="lead text-muted mb-0 pc-da">You can use this platform to interact with employers</p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section class="section-re-de-pa">
      <div class="container">
        <div class="row justify-content-center">
          <div class="text-lg-start"> 
            <!-- ---------------------------- -->
            <div class="card mt-4 pb-3">
            {% for item in nots %}
                
              <div class="d-sm-flex align-items-top p-4">
                <div class="flex-grow-1 ms-sm-3">
                  <div>
                    <p class="texthead text-md-end"> {{item.postedAt}}</p>
                    <h6 class="mt-0 mb-1 fs-16 text-md-start hed-minuslow">{{item.content}}</h6>
                  </div>
                </div>
              </div>
              <hr>
            {% endfor %}
            </div>
            <!-- ---------------------------- -->
            <div class="text-center mt-4 pt-2"> <a href="#" class="btn btn-outline-primary" style="border-radius: 50px;">Load More Notifications <i class="fa fa-long-arrow-right" aria-hidden="true"></i></a> </div>
          </div>
        </div>
      </div>
    </section>
    
    
  </div>

    {% include 'home/_footer.html.twig' %}
{% endblock %}